apiVersion: apps/v1
kind: Deployment
metadata:
  name: siganyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siganyi
  template:
    metadata:
      labels:
        app: siganyi
    spec:
      containers:
      - image: okteto.dev/siganyi:latest
        name: siganyi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "05a14cf2-fab1-4642-a09d-6ee8cd7db58c"
        - name: Vless_Path
          value: "/2ewtr"
        - name: Vmess_UUID
          value: "05a14cf2-fab1-4642-a09d-6ee8cd7db58c"
        - name: Vmess_Path
          value: "/235rg"
        - name: Share_Path
          value: "/Share255"
